Store/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

handler404 = 'Store.views.file_not_found_404'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Store.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^checkout/', include('checkout.urls')),
    url(r'^', include('catalog.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^social/', include('social_auth.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.conf.urls import *

urlpatterns = patterns('cart.views',
                       url(r'^$', 'show_cart_new', { 'template_name': 'cart/cart.html' }, 'show_cart'),
)

catalog/forms.py
# -*- coding: utf-8 -*-
from catalog.models import Product
from django import forms
from catalog.models import Filling


class AddToCart(forms.Form):
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size':'2', 'value':'1', 'class': 'form-control'}),
                                  error_messages={'invalid' : 'Please enter a valid quantity.'},
                                  label='Количество',
                                  min_value=1,
                                  max_value=100)

    def __init__(self, request=None, *args, **kwargs):
        """ override the default so we can set the request """
        self.request = request
        super(AddToCart, self).__init__(*args, **kwargs)

    def clean(self):
        print("add_to_cart")
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError("Cookies must be enabled.")
        return self.cleaned_data

class AddToCartFromCategory(AddToCart):
    product_slug = forms.CharField(widget=forms.HiddenInput())

class AddToCartForm(forms.Form):
    description = forms.CharField (widget=forms.Textarea(attrs={'class':'form-control', 'rows': '3',
                                        'placeholder': "Поздравительная надпись"}),
                                   label='Выбор оформления',
                                   required=False)
    product_slug = forms.CharField(widget=forms.HiddenInput())
    filling_choice = forms.ModelChoiceField(queryset=Filling.active.all(),
                                            empty_label=None,
                                            label="Основа",
                                            widget=forms.Select(attrs={'class':'form-control'}),
                                            )
    weight = forms.FloatField (widget=forms.TextInput(attrs={'size': '2','value':'3.5','class':'form-control',
                                                             'type':'number', 'step':'0.5', 'max':'20',
                                                             'min':'1'}),
                                error_messages={'invalid' : 'Пожалуйста, введите корректное значение!'},
                                min_value=1, max_value=20,
                                label='Вес: ')
    #quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size':'2', 'value':'1', 'class':'quantity'}),
                                 # error_messages={'invalid':'Please enter a valid quantity.'},
                                  #min_value=1)

    def __init__(self, request=None, *args, **kwargs):
        """ override the default so we can set the request """
        self.request = request
        super(AddToCartForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError("Cookies must be enabled.")
        return self.cleaned_data


class ProductAdminForm(forms.ModelForm):
    class Meta:
        model = Product

    def clean_price(self):
        if self.cleaned_data['price'] <= 0:
            raise forms.ValidationError('Price must be greater than zero.')
        return self.cleaned_data['price']

templates/tags/accounts_info.html
{% load staticfiles %}
{% if user.is_authenticated %}
	<p style="">
	    {% if provider == "vk-oauth" %}
	    <img style="max-width: 30px; padding-right: 5px" src="{% static "image/social/vk.png" %}"
	    class="img-social">
	    {% elif provider == "facebook"%}
	    <img style="max-width: 30px; padding-right: 5px" src="{% static "image/social/fb.png" %}"
	    class="img-social">
	    {% elif provider == "odnoklassniki"%}
	    <img style="max-width: 30px; padding-right: 5px" src="{% static "image/social/ok.png" %}"
	    class="img-social">
	    {% elif provider == "vk-oauth"%}
	    <img style="max-width: 30px; padding-right: 5px" src="{% static "image/social/vk.png" %}"
	    class="img-social">
	    {% elif provider == "vk-oauth"%}
	    <img style="max-width: 30px; padding-right: 5px" src="{% static "image/social/vk.png" %}"
	    class="img-social">
	    {% endif %}
	    Добро пожаловать, {{ user_name }}!<span> | </span>
	    <a style=" color: #e2ac79;" href="{% url 'django.contrib.auth.views.logout' %}?next={{request.path|urlencode}}">Выйти</a>
	</p>
{% else %}
	<div class="reg_div" style="">
	    <a href="#" class="get-reg-modal" style="">Зарегистрироваться</a><span > | </span>
	    <a href="#" class="get-login-modal">Войти</a>
	</div>
{% endif %}

templates/tags/fillings.html
<ul>
{% for f in fillings %}
	<li>{{ f.name }}</li>
{% endfor %}
</ul>

templates/tags/fillings_modal.html
<!-- Modal -->
{% load staticfiles %}
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Основа торта</h4>
            </div>
            <div class="modal-body">
                {% for f in fillings %}
                <div class="row">
                    <div class="col-md-12 filling_text">
                        <h3 class="pull-center">{{ f.name }}</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <img class="img-responsive" src="{% static f.image.url %}" alt="">
                    </div>
                    <div class="col-md-6">
                        <p>{{ f.description }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary">Сохранить изменения</button>
            </div>
        </div>
    </div>
</div>

templates/tags/form_table_row.html
<tr>
	<th>
	{% if form_field.field.required %}*{% endif %}
	{{ form_field.label_tag }}
	</th>
	<td>
	{% if form_field.errors %}
		<ul class="errorlist">
		{% for error in form_field.errors %}
			<li>{{ form_field.label }}: {{ error }}</li>
		{% endfor %}
		</ul>
	{% endif %}
			
	{{ form_field }}
	</td>
</tr>

templates/tags/last_products.html
{% load staticfiles %}
<h3 style="font-size: 20px; border-bottom: 1px solid #1F0F06; padding-bottom: 3px; margin-bottom: 20px">Последние просмотренные</h3>
{% for p in last_products %}
	<div class="col-md-6" style="font-size: 14px; text-align: center; padding: 0">
		<div class="thumbnail" style="background-color: #FBE0B9; margin: 4px">
			<a style="color: inherit" href="{{ p.get_absolute_url }}"> <img src="{% static p.image %}" class="img-responsive">
			<div style="padding-top: 5px"><strong>{{ p.name }}</strong></div></a>
		</div>

    </div>
{% endfor %}

templates/tags/navigation.html
{% load catalog_tags %}
<div id = "navigation_list">
	<ul class="nav navbar-nav">
	    <li class=" hidden-xs"><a href="{% url 'catalog' %}"> Каталог</a></li>
		<li class="dropdown visible-xs-block">
			  <a href="#" class="dropdown-toggle" style="" data-toggle="dropdown">
				  <i class="glyphicon glyphicon-picture visible-xs-inline" ></i>
				  Каталог<b class="caret"></b></a>
			  <ul class="dropdown-menu">
				{% category_list request.path  %}
			  </ul>

			</li>
	    <li><a href="{% url 'discounts' %}"><i class="glyphicon glyphicon-gift visible-xs-inline" ></i> Акции</a></li>
	    <li><a href="/delivery/"><i class="glyphicon glyphicon-info-sign visible-xs-inline" ></i> Условия заказа</a></li>
	    <li><a href="/about/"><i class="glyphicon glyphicon-earphone visible-xs-inline" ></i> О нас</a></li>
		<hr style="border-color: #bc742e;margin-bottom: 0" class="visible-xs-block">
		<li class="visible-xs-block"><a href=""><i class="glyphicon glyphicon-shopping-cart icon-white visible-xs-inline"></i> Корзина (1) </a> </li>
	    {% comment %}{% if user.is_authenticated %}{% endcomment %}
	    {% comment %}
	    <li style=" display:block; float:left; position:relative; right:50%;"><a href="{% url 'my_account' %}">Моя страница</a></li>
	    {% endcomment %}
	    {% comment %}{% else %}
	    <li style=" display:block; float:left; position:relative; right:50%;"><a href="#sign_up_modal" data-toggle="modal">Моя страница</a></li>
	    {% endif %}{% endcomment %}
	</ul>
</div>

templates/tags/pop_products.html
{% load staticfiles %}
<div class="pop_products">
	<h3>Популярные товары</h3>
	{% for p in pop_products %}
		<div class="col-md-6 col-sm-12 pop_product_thumb">
			<div class="thumbnail">
			<a href="{{ p.get_absolute_url }}"> <img src="{% static p.image %}" class="img-responsive">
			<div class="pop_product_name" style=""><strong>{{ p.name }}</strong></div></a>
			</div>
		</div>
	{% endfor %}
</div>

templates/tags/product_choice_detail.html
{% load staticfiles %}
{% load catalog_filters %}
<div class="row description_product choice_detail weight-row">
    <form method="post" action="" class="cart" id="cart">
        <div class="col-md-2 col-sm-2">
            <h5> {{ form_cart.weight.label }}</h5>
        </div>
        <div class="col-md-3 col-sm-3q form-group weight-form">
            {{ form_cart.weight }}
        </div>
	    <div class="col-md-1 col-sm-1 weight-kg" >
            кг
        </div>
	    <div class="col-md-6 col-sm-6 error_description weight-errors"  id = '{{ form_cart.weight.name  }}_error' >
            {{ form_cart.weight.errors }}
		</div>
</div>
<div class="row description_product choice_detail">
    <div class="col-md-12">
        <h5 style="margin-top: 0px ">{{ form_cart.description.label }}:
        </h5>
        <div class="">
	        <div class="">
		        {{ form_cart.description }}
	        </div>
	        <span class="help-block">
		        В зависимости от Ваших пожеланий, верхушка торта может быть украшена поздравительной надписью (бесплатно)
	        </span>
            <div class="col-md-12 help_line" id = '{{ form_cart.description.name  }}_error' >
                {{ form_cart.description.errors }}
            </div>
        </div>
        <h5>{{ form_cart.filling_choice.label }}:</h5>
        <div class="input-group">
            <span class="input-group-btn">
            <button class="btn btn-default" data-toggle="modal" data-target="#myModal" type="button">?</button></span>
            {{ form_cart.filling_choice }}
        </div>
        <span  class="help-block">Различные варианты выбора начинки торта. Нажмите "?" для просмотра более подробной информации </span>
    </div>
</div>
<div class="row price_cart choice_detail">
    <div class="col-md-7" style="padding-right: 0">
        <div class="price">{{ p.price|currency }} <span style="font-size: 16px"> (за кг) </span></div>
    </div>
    <div class="col-md-5 add_cart" style="padding-left: 0">
        {% csrf_token %}
        <button type="submit" id="add_button" class="btn pull-right" >
        В корзину  <i class="glyphicon glyphicon-shopping-cart icon-white"></i>
        </button>
        {{ form_cart.product_slug }}
        </form>
        <a id="go_cart" class="pull-right"  href="{% url 'show_cart' %}">Перейти в корзину <i class="glyphicon glyphicon-shopping-cart icon-white"></i></a>
    </div>
</div>
<!-- Написать HTML -->
{% comment %}<a href="#" id="example" data-toggle="tooltip" title="Some tooltip text!">Hover over me</a>{% endcomment %}
<!-- Создание разметки с помощью плагина -->
<div class="tooltip top" role="tooltip">
  <div class="tooltip-arrow"></div>
  <div class="tooltip-inner">
    В зависимости от Ваших пожеланий, верхушка торта может быть украшена поздравительной надписью.
	Окончательная стоимость торта зависит только от выбора его веса - дополнительное оформление надписью является бесплатным.
  </div>
</div>

templates/tags/product_detail.html
{% load staticfiles %}
{% load catalog_filters %}
<div class="row description_product detail count-row" >
	<form method="post" action="" class="cart" id="cart">
    <div class="col-md-4 ">
        <h5> {{ form_cart.quantity.label }}</h5>
    </div>
    <div class="col-md-3 form-group count-form" >
        {{ form_cart.quantity }}
    </div>
    <div class="col-md-5 help_line" id = '{{ form_cart.quantity.name  }}_error'>
	    {{ form_cart.quantity.errors  }}
    </div>
</div>
<div class="row detail description_product  ">
	<div class="col-md-12 des">
		<h5>Описание:</h5>
	</div>

</div>
<div class="row detail">
	<div class="col-md-12">
		<p class="description_name">{{ p.description }}</p>
	</div>

</div>
<div class="row price_cart detail">
                <div class="col-md-6 ">
                    <div class="price"> {{ p.price|currency }}</div>
                </div>
                <div class="col-md-6 add_cart">
                    <form method="post" action="" class="cart" id="cart">
                        {% csrf_token %}
                        <button type="submit" id="add_button" class="btn pull-right" >
	                        В корзину  <i class="glyphicon glyphicon-shopping-cart icon-white"></i>
                        </button>
	                    {{ form_cart.product_slug }}

                    </form>
	                <a id="go_cart" class="pull-right" href="{% url 'show_cart' %}">Перейти в корзину <i class="glyphicon glyphicon-shopping-cart icon-white"></i></a>
                </div>
            </div>

templates/tags/product_thumbnail.html
{% load staticfiles %}
{% load catalog_filters %}
{% for p in products%}
<div class=" col-md-6 col-sm-6 col-xs-12 products_min ">
    <div class="product_thumbnail">
    {% if discount %} <img class="discounts_img img-responsive" src="{% static "bootstrap/img/1212.gif" %}"> {% endif %}
        <div class="thumbnail  {% if discount %} discounts {% endif %}">
            <div>
                {% if p.detail %}
                <a href="{{ p.get_absolute_url }}">
                <img id="" class="img-responsive lazy_load" data-original="{% static p.image %}" src="{% static p.image %}" alt="{{ p.name }}">
                </a>
                {% else %}
                <a title="{{ p.name }}" href="{% static p.image %}" data-gallery><img id="target" class="img-responsive" src="{% static p.image.url %}" alt=""></a>
                {% endif %}
            </div>
            <div class="caption">
                {% if p.detail %}
                <a href="{{ p.get_absolute_url }}">
                    <h4 class="name_product"> {{ p.name }}
                    </h4>
                </a>
                {% else %}
				     <a href="{% static p.image %}" data-gallery><h4 class="name_product">
					     {{ p.name }}
                    </h4></a>
                {% endif %}
                <hr>
                <div class="row price_weight" >
                    <div class="col-md-7 col-sm-7 col-xs-7 about_order" >
                        <div class="thumb_price {%  if p.old_price > 0  %} new_price_div {% endif %}">

	                        {%  if p.old_price > 0  %}
		                        <span class="new_price"> {{ p.price|currency }}</span>
	                            <span class="old_price">{{ p.old_price|currency }}</span>
                            {% elif p.weight %}
		                        <span class="price"> {{ p.price|currency }}
		                        <span class="weight-price">| {{ p.weight }} кг</span> </span>
	                        {% else %}
	                        <span> {{ p.price|currency }}</span>
	                        {% endif %}
                        </div>
                    </div>
                    <div class="col-md-5 col-sm-5 col-xs-5 add_order">
	                    {% if not p.choice_weight %}
		                    <form method="post" action="." class="cart add_form" id="{{ p.slug }}">
	                            {% csrf_token %}
			                    <input id="id_product_slug" name="product_slug" value="{{ p.slug}}" type="hidden">
			                    <button id="{{ p.slug }}_button" class="btn add_button" type="submit">В корзину
				                    <i class="glyphicon glyphicon-shopping-cart icon-white"></i></button>
							</form>
	                    {% else %}
		                    <a href="{{ p.get_absolute_url }}">
			                    <div class = "btn add_button">Подробнее</div>
		                    </a>
	                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

templates/tags/register.html
{% load staticfiles %}
<div class="modal fade" id="sign_up_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog my_modal">
        <div class="modal-content my_modal_content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Вход на сайт</h4>
            </div>
            <div class="modal-body">
                <ul class="nav nav-tabs" id="login-or-register">
                    <li class="active"><a href="#login-tab" data-toggle="tab" id="li_login">Авторизация</a></li>
                    <li ><a href="#register" data-toggle="tab" id="li_register">Регистрация</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="login-tab">
                        <div class="alert alert-danger" id = "login_errorlist">
                            <h5></h5>
                            <div class="error_description">
                            </div>
                        </div>
                        <form method="post" action="{% url 'login' %}" id="login_form">
                            {% csrf_token %}
                            <span class=" reg_label">
	                            <label class="label_name">
	                                {{ auth_form.username.label }}:
	                            </label>
                            </span>
                            <span class="reg_form">
                                {{ auth_form.username }}
                            </span>
                            <span class=" reg_label">
	                            <label class="label_name">
	                                {{ auth_form.password.label }}:
	                            </label>
                            </span>
                            <span class="reg_form">
                                {{ auth_form.password }}
                            </span>
	                        <hr>
	                        <div class="social-text">
	                            <p>
	                                Для входа на сайт вы можете также использовать свой аккаунт в одном из этих сервисов:
	                            </p>
	                        </div>
	                        <div class="social-icon center-block " id="parent">
	                            <div class="child">
		                            <a href="{% url 'socialauth_begin' 'vk-oauth' %}?next={{ request.path }}">
	                                    <img src="{% static "image/social/vk.png" %}" class="img-social">
			                        </a>
	                            </div>
	                            <div class="child">
		                            <a href="{% url 'socialauth_begin' 'facebook' %}?next={{ request.path }}">
	                                    <img src="{% static "image/social/fb.png" %}" class="img-social">
			                        </a>
	                            </div>
	                            {% comment %}<div class="child">
		                            <a href="{% url 'socialauth_begin' 'github' %}?next={{ request.path }}">
	                                    <img src="{% static "image/social/gh.png" %}" class="img-social">
			                        </a>
	                            </div>{% endcomment %}
	                            <div class="child">
		                            <a href="{% url 'socialauth_begin' 'odnoklassniki' %}">
	                                    <img src="{% static "image/social/ok.png" %}" class="img-social">
			                        </a>
	                            </div>

	                        </div>
	                        <div class="modal-footer">
	                            <input type="hidden" name="next" value="{{ request.path }}" />
	                            <button type="submit" class="btn btn-primary " id = "login_button">Войти</button>
	                            <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
	                        </div>
	                    </form>
                    </div>
                    <div class="tab-pane" id="register">
                        <form action="{% url 'register_ajax' %}" method="post" id = "reg_form">
                            {% csrf_token %}
                            <span class=" reg_label">
	                            <label class="label_name">
	                                {{ reg_form.name.label }}:
	                            </label>
                            </span>
                            <span class="reg_form">
                                {{ reg_form.name }}
                            </span><span class="help-block errors_text"  id = '{{ reg_form.name.name  }}_error'></span>
                            <span class="help-block">
                                {{ reg_form.name.help_text }}
                            </span>

                            <span class="reg_label">
	                            <label class="label_name">
	                            {{ reg_form.email.label }}:
	                            </label>
                            </span>
                            <span class="reg_form">
                                {{ reg_form.email }}
                            </span>
                            <span class="help-block errors_text"  id = '{{ reg_form.email.name  }}_error'></span>
	                        <span class="help-block">
                                {{ reg_form.email.help_text }}
                            </span>
                            <span class="reg_label">
	                            <label class="label_name">
	                            {{ reg_form.password1.label }}:
	                            </label>
                            </span>
                            <span class="reg_form">
                                {{ reg_form.password1 }}
                            </span>
                            <span class="help-block">
                                {{ reg_form.password1.help_text }}
                            </span>
	                        <span class="help-block errors_text"  id = '{{ reg_form.password1.name  }}_error'></span>
                            <span class="reg_label">
	                            <label class="label_name">
	                                {{ reg_form.password2.label }}:
	                            </label>
                            </span>
                            <span class="reg_form">
                                {{ reg_form.password2 }}
                            </span>
                            <span class="help-block errors_text"  id = '{{ reg_form.password2.name  }}_error'></span>
                            <div class="modal-footer">
	                            <input value="" type="hidden" name="next_page">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                                <button type="submit" class="btn btn-primary " id = "reg_button">Зарегестрироваться</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/tags/robokassa.html
{% load staticfiles %}
<div class="modal fade" id="robokassa_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog my_modal">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Способы оплаты</h4>
            </div>
            <div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<img src="{% static "image/robokassa-valuta.jpg" %}" class="img-responsive">
					</div>
				</div>
            </div>
        </div>
    </div>
</div>

templates/tags/search_box.html
<form id="search" action="{% url 'search_results' %}" method="get" class="form-search">
	{{ form.q }}
</form>

templates/tags/show_product_modal.html
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">{{ p.name }}</h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
</div>